version: "3.8"

services:
  frontend:
    depends_on:
      - backend1
    build: ./frontend
    ports:
      - 3000:3000

  backend1:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db1/vidly
    command: ./docker-entrypoint.sh

  db1:
    image: mongo:4.0-xenial
    container_name: db1
    ports:
      - 27017:27017
    volumes:
      - vidly1:/data/db

  db2:
    image: mongo:4.0-xenial
    container_name: db2
    ports:
      - 27018:27017
    volumes:
      - vidly2:/data/db

volumes:
  vidly1:
  vidly2:
